name: Edit Initial Templates

on: 
  workflow_dispatch:
    inputs:
      ORGANIZATION_NAME:
        description: 'Name of the organization in GitHub that will be set in the cloud-deployment and cloud-infrastructure templates'
        type: string

jobs:    
  edit-template:
    name: Edit Templated Repository
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4
        name: Checkout cloud-manager
      - uses: ./.github/workflows/actions/hcl-edit-and-merge
        name: Edit cloud-deployment HCL for root
        with: 
          GITHUB_TOKEN: ${{ secrets.CLOUD_DEPLOYMENT_PAT }}
          REPO_TO_EDIT: ${{ inputs.ORGANIZATION_NAME }}/cloud-deployment
          FILE_TO_EDIT: live/aws/terragrunt.hcl
          FIELD_TO_EDIT: locals.organization_name
          VALUE_TO_SET: ${{ inputs.ORGANIZATION_NAME }}
          BRANCH_NAME: template/edit-root-organization-name
          COMMIT_MESSAGE: Update organization name for root
      - uses: ./.github/workflows/actions/hcl-edit-and-merge
        name: Edit cloud-deployment HCL for cloudscape
        with: 
          GITHUB_TOKEN: ${{ secrets.CLOUD_DEPLOYMENT_PAT }}
          REPO_TO_EDIT: ${{ inputs.ORGANIZATION_NAME }}/cloud-deployment
          FILE_TO_EDIT: live/aws/cloudscape/terragrunt.hcl
          FIELD_TO_EDIT: locals.organization_name
          VALUE_TO_SET: ${{ inputs.ORGANIZATION_NAME }}
          BRANCH_NAME: template/edit-cloudscape-organization-name
          COMMIT_MESSAGE: Update organization name for cloudscape
      - uses: ./.github/workflows/actions/hcl-edit-and-merge
        name: Edit cloud-infrastructure HCL for cloudscape
        with: 
          GITHUB_TOKEN: ${{ secrets.CLOUD_DEPLOYMENT_PAT }}
          REPO_TO_EDIT: ${{ inputs.ORGANIZATION_NAME }}/cloud-infrastructure
          FILE_TO_EDIT: iac/aws/cloudscape/locals.hcl
          FIELD_TO_EDIT: locals.organization_name
          VALUE_TO_SET: ${{ inputs.ORGANIZATION_NAME }}
          BRANCH_NAME: template/edit-cloudscape-organization-name
          COMMIT_MESSAGE: Update organization name for cloudscape