name: Initialize Terraform State and Lock

on: 
  workflow_dispatch:
    inputs:
      ORGANIZATION_NAME:
          description: 'Name of the organization to use for the terraform state and lock'
          type: string

jobs:    
  initialize-terraform:
    name: Run initial iac for state and lock infrastructure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout cloud-manager
      - uses: hashicorp/setup-terraform@v3
        name: Install Terraform
      - name: Initialize Terraform
        run: |
          cd iac
          terraform init
          terraform apply -auto-approve -var="organization_name=${{ inputs.ORGANIZATION_NAME }}"
        