name: Update AWS Credentials

on:
  workflow_dispatch:
    inputs:
      repository_owner:
        required: true
        type: text
      repos_to_update: 
        default: "['cloud-deployment', 'test-poc']"
        # required: true
        type: string
      github_token:
        required: true
        type: text

concurrency: one-deploy-at-a-time

jobs:
  update:
    name: Update Credentials
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - run: |
          echo "${{fromJson(inputs.repos_to_update)}}"


      - name: Set Secret
        run: |
          echo ${{ inputs.github_token }}
          array=${{ fromJson(inputs.repos_to_update) }}
          for repo in "${array[@]}"; do 
            echo "$repo"
            gh secret set AWS_ACCESS_KEY_ID5 -b "${{ secrets.AWS_ACCESS_KEY_ID }}" -R ${{ inputs.repository_owner }}/"$repo"
          done
        env:
          GH_TOKEN: ${{ inputs.github_token }}