name: Update AWS Credentials

env:
  REPOS: ('cloud-deployment', 'test-poc')

on:
  workflow_dispatch:
    inputs:
      repository_owner:
        required: true
        type: text
      repo_to_update:
        required: true
        type: text
      github_token:
        required: true
        type: text


concurrency: one-deploy-at-a-time

jobs:
  update:
    name: Update Credentials
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Secret
        run: |
          echo ${{ inputs.github_token }}
          for repo in $REPOS; do 
            echo $repo
          done
          gh secret set AWS_ACCESS_KEY_ID2 -b "${{ secrets.AWS_ACCESS_KEY_ID }}" -R ${{ inputs.repository_owner }}/${{ inputs.repo_to_update }}
        env:
          GH_TOKEN: ${{ inputs.github_token }}