name: Update AWS Credentials

on:
  workflow_dispatch:
    inputs:
      repository_owner:
        description: name of the repo owner
        required: true
        type: string
      repos_to_update: 
        description: which repos to distribute creds to
        required: true
        type: string
      github_token:
        description: token to access all affected repos
        required: true
        type: string

concurrency: one-deploy-at-a-time

jobs:
  update:
    name: Update Credentials
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Secrets
        run: |
          for repo in ${{ inputs.repos_to_update }}; do 
            echo "$repo"
            gh secret set AWS_ACCESS_KEY_ID -b "${{ secrets.AWS_ACCESS_KEY_ID }}" -R ${{ inputs.repository_owner }}/"$repo"
            gh secret set AWS_SECRET_ACCESS_KEY -b "${{ secrets.AWS_SECRET_ACCESS_KEY }}" -R ${{ inputs.repository_owner }}/"$repo"
            gh secret set CLOUD_DEPLOYMENT_PAT -b "${{ secrets.CLOUD_DEPLOYMENT_PAT }}" -R ${{ inputs.repository_owner }}/"$repo"
            gh secret set DASHG_CLOUD_PLATFORM_PAT -b "${{ secrets.DASHG_CLOUD_PLATFORM_PAT }}" -R ${{ inputs.repository_owner }}/"$repo"
          done
        env:
          GH_TOKEN: ${{ inputs.github_token }}